name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: temurin
      - name: Publish package
        run: |
          git --no-pager log -1 --name-only -p
          git branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}