name: Build

on:
  push:
    branches:
      - master
      - newbranch
      - qa

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
      - uses: tj-actions/changed-files@v20
      - name: Publish package
        run: |
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            echo "$file was modified"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}