name: Run job

on:
  repository_dispatch:
    types: selective-build-and-deploy

jobs:
  get-all-payload:
    name: Get all the payload
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: get payload
        run: |
          sasa=$github.event.client_payload.services
          echo $#sasa[*]
          for service in "${{ github.event.client_payload.services[1] }}"; do
            echo $service
          done
          
          echo ${{ github.event.client_payload.env }}
