name: Run job

on:
  repository_dispatch:
    types: selective-build-and-deploy

jobs:
  get-all-payload:
    name: Get all the payload
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        service: ${{ github.event.client_payload.services }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch }}
      - name: get payload
        if: github.event.client_payload.env == 'dev'
        env:
          SERVICE: ${{ matrix.service }}
        run: |
          echo "./gradlew :${{ env.SERVICE }}:build"