name: Build

on:
  push:
    branches:
      - master
      - newbranch

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v11.9
      - name: List all modified files
        run: |
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            echo "$file was modified"
          done
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: temurin
      - name: Publish package
        run: |
          git --no-pager log -1 --name-only -p
          git branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}