name: Run job

on:
  repository_dispatch:
    types: selective-build-and-deploy

jobs:
  get-all-payload:
    name: Get all the payload
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: get payload
        run: |
          #for service in "${{ github.event.client_payload.services[0] }}"; do
          #  echo $service
          #done
          
          services=${{github.event.client_payload.services}}
          s=join(services, ',')
          echo $services
          echo $s
          
          echo ${{ github.event.client_payload.env }}
